[dependency-groups]
auto-test = [{ include-group = "test" }, "tox>=4.23.2"]
dev = [
  { include-group = "auto-test" },
  { include-group = "lint" },
  { include-group = "manual-test" },
  { include-group = "test" },
  { include-group = "type" },
]
lint = ["ruff>=0.11.13"]
manual-test = [{ include-group = "test" }, "pytest-sugar>=1.0.0"]
test = ["pre-commit>=4.0.1", "pytest>=8.4.0", "pytest-cov>=6.0.0"]
type = [{ include-group = "test" }, "mypy>=1.16.0"]

[project]
authors = [{ name = "ProFatXuanAll", email = "ProFatXuanAll@gmail.com" }]
description = "ProFatXuanAll.github.io"
dependencies = [
  "furo>=2024.8.6",
  "sphinx>=8.2.3",
  "sphinx-autobuild>=2024.10.3",
  "sphinx-copybutton>=0.5.2",
  "sphinx-design>=0.6.1",
  "sphinxcontrib-bibtex>=2.6.3",
  "sphinxcontrib-mermaid>=1.0.0",
]
license = { text = "MIT" }
name = "ProFatXuanAll.github.io"
readme = "README.md"
requires-python = ">=3.12"
version = "0.0.0"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.xml]
output = "coverage.xml"

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax", "Unpack"]
python_version = "3.12"

[tool.pdm]
distribution = false

[tool.pdm.scripts]
lint = "ruff --config pyproject.toml check --fix src tests"
doc-build = "sphinx-build -E -b html doc/source doc/build"
doc-build-coverage = "sphinx-build -E -b coverage doc/source doc/build"
doc-dev = "sphinx-autobuild --host 0.0.0.0 --port 8000 --watch . --open-browser doc/source doc/build"
test = "pytest --config-file=pyproject.toml"
type = "mypy --config-file=pyproject.toml src tests"

[tool.pytest.ini_options]
addopts = "--cov=src --cov-config=pyproject.toml --cov-report term --cov-report xml --junit-xml=report.xml tests"

[tool.ruff]
include = ["*.py", "*.pyi"]
indent-width = 2
line-length = 120
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 120
line-ending = "lf"
quote-style = "single"

[tool.ruff.lint]
ignore = [
  "COM819",
  "CPY",
  "D203",
  "D213",
  "D413",
  "D416",
  "E111",
  "E114",
  "FA",
  "W191",
  "W505",
]
select = [
  "A",
  "AIR",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "COM",
  "D",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FBT",
  "FIX",
  "FLY",
  "FURB",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "LOG",
  "N",
  "NPY",
  "PD",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "T20",
  "TD",
  "TID",
  "TRY",
  "UP",
  "W",
  "YTT",
]
task-tags = ["TODO", "FIXME"]
unfixable = ["B007", "ERA", "F401", "F841"]

[tool.ruff.lint.flake8-annotations]
suppress-dummy-args = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"typing.Dict".msg = "Use dict instead."
"typing.List".msg = "Use list instead."

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]

[tool.ruff.lint.isort]
case-sensitive = true

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.pylint]
max-args = 20
max-statements = 100

[tool.tox]
env_list = ["lint", "type", "py312"]
requires = ["tox>=4"]
skip_missing_interpreters = true

[tool.tox.env.doc]
commands = [["sphinx-build", "-E", "-b", "html", "doc/source", "doc/build"]]
dependency_groups = ["doc"]
description = "build documents"

[tool.tox.env.lint]
commands = [
  [
    "ruff",
    "--config",
    "pyproject.toml",
    "check",
    "--fix",
    "src",
    "tests",
  ],
]
dependency_groups = ["lint"]
description = "run linters"
skip_install = true

[tool.tox.env.type]
commands = [["mypy", "--config-file=pyproject.toml", "src", "tests"]]
dependency_groups = ["type"]
description = "run static type checks"
